//! Fortified cities in play. The layout is generated by `crate::fortress`; walls are pinned
//! `RockKind::Wall` bodies (solid, tough, destroyable, no loot, never mined, remembered as
//! fallen by spawn index like any other kill) and turrets are `BaseKind::Turret` bases.
//!
//! - **Walls** block ships, creatures and every shot. Enemy fire and enemy blasts never wear a
//!   wall down (so a turret cannot shoot its own wall away); the ship's weapons, mines and
//!   rams do, and a breach is permanent for the session (and persisted by spawn index).
//! - **Turrets** aim within a fire arc, fire the pattern of the territory's own genes
//!   (`Territory::turret_arms`) when the ship is in reach and a clear line exists (walls in
//!   the way stop the volley, so corridors and corners are cover), and a gate turret keeps a
//!   mine or two laid at its chokepoint. A fallen civilization's turrets go quiet.
//! - **Budget.** A fortress is generated inside a body budget (`crate::fortress`); on load,
//!   pieces are skipped once the world is within `RESERVE` bodies of `MAX_BODIES`.

use super::weapons::{MINE_BLAST, MINE_DAMAGE, Muzzle, pace};
use super::*;
use crate::fortress::{FortPart, MUZZLE_GAP, PartKind};
use crate::territory::Standing;

/// Fortress pieces are not placed within this many bodies of the cap, so shattering,
/// breeding and raids always have room.
pub const RESERVE: usize = 220;
/// How far a turret shoots, and how fast its shots fly.
pub const TURRET_REACH: f32 = 950.0;
const SHOT_SPEED: f32 = 380.0;
/// Seconds between a turret's volleys at neutral aggression, and how fast its barrel turns.
const PERIOD: f32 = 3.2;
const TURN: f32 = 5.0;
/// A gate turret lays a mine when the ship is within this of the spot, at most two stand
/// there at once, and it lays no faster than every `LAY_PERIOD` seconds.
const LAY_SIGHT: f32 = 1500.0;
const LAY_PERIOD: f32 = 9.0;
const LAY_MAX: usize = 2;

/// Shortest signed angle from `from` to `to`.
fn turn_between(from: f32, to: f32) -> f32 {
    (to - from + PI).rem_euclid(TAU) - PI
}

impl Game {
    /// True when no wall lies across the segment (a shot would reach).
    pub fn clear_shot(&self, from: Vec2, to: Vec2) -> bool {
        !self.bodies.iter().any(|b| {
            b.active
                && b.rock == RockKind::Wall
                && segment_circle(from, to, b.position, b.radius + 3.0).is_some()
        })
    }

    /// Per tick: every loaded turret aims, fires and (at a gate) lays mines.
    pub(super) fn update_turrets(&mut self, dt: f32) {
        let ids: Vec<u64> = self
            .bodies
            .iter()
            .filter(|b| b.active && b.base.as_ref().is_some_and(|s| s.kind == BaseKind::Turret))
            .map(|b| b.id)
            .collect();
        let ship = self.player().map(|p| p.position);
        for id in ids {
            let Some(index) = self.bodies.iter().position(|b| b.id == id) else {
                continue;
            };
            let body = &self.bodies[index];
            let Some(FortPart {
                kind: PartKind::Turret { facing, arc, lay },
                ..
            }) = body.fort
            else {
                continue;
            };
            let (position, genes, radius) = (body.position, body.genes, body.radius);
            let live = body
                .origin
                .and_then(|o| self.civ_works.get(&o))
                .is_none_or(|(tid, _)| {
                    self.civ_standing(*tid) != Standing::Fallen && self.civ_hostile(*tid)
                });
            let aggression = genes.aggression.max(0.3);
            // The barrel follows the ship inside its arc and rests facing out otherwise.
            let aim_at = ship.filter(|s| s.distance(position) < TURRET_REACH);
            let want = match aim_at {
                Some(s) => {
                    let delta = turn_between(facing, (s - position).to_angle());
                    (delta.abs() <= arc).then_some(facing + delta)
                }
                None => None,
            };
            let rest = want.unwrap_or(facing);
            let angle = self.bodies[index].angle;
            let step = turn_between(angle, rest).clamp(-TURN * dt, TURN * dt);
            self.bodies[index].angle = angle + step;
            let Some(state) = self.bodies[index].base.as_mut() else {
                continue;
            };
            state.turrets[0] -= dt;
            state.turrets[1] -= dt;
            let Some((weapon, volley)) = state.arms else {
                continue;
            };
            if !live {
                continue;
            }
            let (fire_ready, lay_ready) = (state.turrets[0] <= 0.0, state.turrets[1] <= 0.0);
            if let (true, Some(target), Some(aim)) = (fire_ready, aim_at, want)
                && turn_between(self.bodies[index].angle, aim).abs() < 0.2
            {
                let direction = Vec2::from_angle(aim);
                let origin = position + direction * (radius + MUZZLE_GAP);
                if self.clear_shot(origin, target) && !self.inside_wall(origin) {
                    let spin = self.bodies[index].spin;
                    let muzzle = Muzzle {
                        origin,
                        aim: direction,
                        velocity: Vec2::ZERO,
                        reach: TURRET_REACH,
                        shot_speed: SHOT_SPEED,
                        sharpness: genes.sharpness(),
                    };
                    let spin = self.discharge(weapon, volley, &muzzle, spin);
                    self.bodies[index].spin = spin;
                    if let Some(state) = self.bodies[index].base.as_mut() {
                        state.turrets[0] = PERIOD * pace(weapon) / aggression;
                    }
                }
            }
            if let (true, Some(spot), Some(target)) = (lay_ready, lay, ship) {
                let near = spot.distance(target) < LAY_SIGHT;
                let standing = self
                    .mines
                    .iter()
                    .filter(|m| !m.friendly && m.position.distance(spot) < 130.0)
                    .count();
                if near && standing < LAY_MAX {
                    let nudge =
                        Vec2::from_angle(2.4 * standing as f32 + 0.7) * 34.0 * standing as f32;
                    self.lay_mine(Mine {
                        position: spot + nudge,
                        velocity: Vec2::ZERO,
                        friendly: false,
                        age: 0.0,
                        fuse: None,
                        damage: MINE_DAMAGE * genes.sharpness(),
                        blast: MINE_BLAST,
                    });
                }
                if let Some(state) = self.bodies[index].base.as_mut() {
                    state.turrets[1] = LAY_PERIOD / aggression;
                }
            }
        }
    }

    /// True when a point lies inside a wall segment.
    fn inside_wall(&self, at: Vec2) -> bool {
        self.bodies.iter().any(|b| {
            b.active && b.rock == RockKind::Wall && b.position.distance(at) < b.radius + 2.0
        })
    }

    /// Wall segments and turrets currently loaded (for budgets and tests).
    pub fn fort_bodies(&self) -> usize {
        self.bodies.iter().filter(|b| b.fort.is_some()).count()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::fortress::{Archetype, PartKind};
    use crate::genome::Weapon;
    use crate::simulation::tests::{DT, set_player};
    use crate::territory::{CivRole, CivShape, Territory};

    const SEED: u64 = 0x535343;

    /// A territory capital sector of the wanted fortress archetype.
    fn capital(seed: u64, wanted: Archetype) -> Territory {
        for x in -40..=40 {
            for y in -40..=40 {
                if let Some(t) = world::territory(seed, SectorId { x, y })
                    && t.capital == (SectorId { x, y })
                    && t.fort_archetype() == wanted
                {
                    return t;
                }
            }
        }
        panic!("no {wanted:?} capital");
    }

    fn visit(seed: u64, at: Vec2) -> Game {
        let mut game = Game::new(seed);
        game.player_invulnerability = 1e9;
        game.teleport(at);
        game.step(DT, Input::default());
        // Fortress guns fire only at an enemy (a civilization that ignores the ship holds fire).
        game.provoke_all();
        game
    }

    fn walls(game: &Game) -> Vec<&Body> {
        game.bodies
            .iter()
            .filter(|b| b.rock == RockKind::Wall)
            .collect()
    }

    #[test]
    fn capitals_have_deterministic_fortresses_inside_the_budget_and_home_has_none() {
        let mut seen = 0;
        for seed in [1_u64, 42, SEED] {
            for x in -30..=30 {
                for y in -30..=30 {
                    let id = SectorId { x, y };
                    let spawns = world::generate(seed, id);
                    assert_eq!(spawns, world::generate(seed, id));
                    let forts: Vec<_> = spawns.iter().filter(|s| s.fort.is_some()).collect();
                    if forts.is_empty() {
                        continue;
                    }
                    seen += 1;
                    let t = world::territory(seed, id).expect("forts only in territories");
                    let capital = t.capital == id;
                    assert!(forts.len() <= if capital { 130 } else { 34 });
                    assert!(
                        forts
                            .iter()
                            .all(|s| s.civ.is_some_and(|c| c.territory == t.id))
                    );
                    assert!(forts.iter().all(|s| {
                        s.index as usize
                            >= spawns.iter().filter(|o| o.apex.is_none()).count() - forts.len()
                    }));
                    assert!(
                        forts
                            .iter()
                            .all(|s| s.pinned == (s.kind == BodyKind::Asteroid))
                    );
                }
            }
        }
        assert!(seen > 10, "fortresses should exist");
        for seed in [1_u64, 42, SEED] {
            assert!(
                world::generate(seed, SectorId::ORIGIN)
                    .iter()
                    .all(|s| s.fort.is_none())
            );
        }
    }

    #[test]
    fn every_generated_fortress_can_be_entered_around_what_the_sector_holds() {
        let mut checked = 0;
        for seed in [7_u64, 42, SEED] {
            for x in -36..=36 {
                for y in -36..=36 {
                    let id = SectorId { x, y };
                    let Some(t) = world::territory(seed, id) else {
                        continue;
                    };
                    let spawns = world::generate(seed, id);
                    let forts: Vec<_> = spawns.iter().filter(|s| s.fort.is_some()).collect();
                    if forts.is_empty() {
                        continue;
                    }
                    // The seat is the base nearest the fortress centroid.
                    let centroid =
                        forts.iter().map(|s| s.position).sum::<Vec2>() / forts.len() as f32;
                    let heart = spawns
                        .iter()
                        .filter(|s| {
                            s.civ.is_some_and(|c| {
                                matches!(c.role, CivRole::Capital | CivRole::Outpost)
                            })
                        })
                        .min_by(|a, b| {
                            a.position
                                .distance(centroid)
                                .total_cmp(&b.position.distance(centroid))
                        })
                        .unwrap();
                    let mut discs: Vec<(Vec2, f32)> = forts
                        .iter()
                        .map(|s| (s.position, s.radius.unwrap()))
                        .collect();
                    discs.extend(
                        spawns
                            .iter()
                            .filter(|s| {
                                s.fort.is_none()
                                    && (s.pinned || matches!(s.kind, BodyKind::BlackHole))
                            })
                            .map(|s| (s.position, s.radius.unwrap_or(300.0))),
                    );
                    assert!(
                        crate::fortress::connected(heart.position, 1100.0, &discs),
                        "{seed} {id:?} {:?} sealed",
                        t.fort_archetype()
                    );
                    checked += 1;
                }
            }
        }
        assert!(checked > 20);
    }

    #[test]
    fn walls_stop_ships_and_every_shot_and_only_friendly_fire_wears_them_down() {
        let t = capital(SEED, Archetype::Ring);
        let mut game = visit(SEED, t.capital.center());
        let wall = walls(&game)[0].clone();
        let (id, health) = (wall.id, wall.health);
        assert!(wall.pinned && wall.max_health > 100.0 && wall.origin.is_some());
        let out = (wall.position - t.capital.center()).normalize_or_zero();
        // The ship pushed into the wall stays outside it.
        for _ in 0..90 {
            set_player(&mut game, wall.position + out * 140.0, -out * 300.0);
            game.step(DT, Input::default());
            let ship = game.player().unwrap().position;
            let w = game.body(id).unwrap();
            assert!(
                ship.distance(w.position) >= w.radius + 13.0,
                "ship inside a wall"
            );
        }
        // A hostile shot is absorbed and does no damage.
        game.bullets.clear();
        let from = wall.position + out * 90.0;
        game.bullets
            .push(Bullet::hostile(from, -out * 300.0, 3.0, 50.0));
        for _ in 0..30 {
            set_player(&mut game, from + out * 400.0, Vec2::ZERO);
            game.step(DT, Input::default());
        }
        assert!(
            game.bullets.iter().all(|b| b.friendly || b.damage != 50.0),
            "the wall absorbed the shot"
        );
        assert_eq!(game.body(id).unwrap().health, health);
        // A friendly shot is absorbed too (even a piercing one) and wears it down.
        let mut shot = Bullet::friendly(from, -out * 600.0, 3.0);
        shot.pierce = 3;
        game.bullets.push(shot);
        for _ in 0..20 {
            set_player(&mut game, from + out * 400.0, Vec2::ZERO);
            game.step(DT, Input::default());
        }
        assert!(
            game.bullets
                .iter()
                .all(|b| !b.friendly || b.velocity.length() < 590.0),
            "the piercing shot stopped"
        );
        assert!(game.body(id).is_none_or(|w| w.health < health));
    }

    #[test]
    fn a_destroyed_segment_leaves_no_loot_and_stays_gone_across_unload_and_reload() {
        let t = capital(SEED, Archetype::Star);
        let mut game = visit(SEED, t.capital.center());
        let before = walls(&game).len();
        let wall = walls(&game)[3].clone();
        game.pickups.clear();
        let score = game.score;
        game.bodies
            .iter_mut()
            .find(|b| b.id == wall.id)
            .unwrap()
            .health = 0.0;
        game.step(DT, Input::default());
        assert!(game.body(wall.id).is_none());
        assert!(
            game.pickups.is_empty() && game.score == score,
            "no loot, no score"
        );
        assert!(
            walls(&game)
                .iter()
                .all(|w| w.radius == crate::fortress::SEG_RADIUS),
            "no shards"
        );
        game.teleport(Vec2::ZERO);
        for _ in 0..5 {
            game.step(DT, Input::default());
        }
        assert!(walls(&game).is_empty());
        game.teleport(t.capital.center());
        for _ in 0..5 {
            game.step(DT, Input::default());
        }
        assert_eq!(walls(&game).len(), before - 1);
        assert!(walls(&game).iter().all(|w| w.origin != wall.origin));
    }

    #[test]
    fn walls_are_never_mined_or_eaten() {
        let t = capital(SEED, Archetype::Grid);
        let game = visit(SEED, t.capital.center());
        assert!(
            walls(&game)
                .iter()
                .all(|w| !w.minable() && !crate::simulation::ecology::edible(w))
        );
    }

    #[test]
    fn turrets_fire_the_pattern_of_the_territorys_genes() {
        let mut checked = 0;
        for archetype in Archetype::ALL {
            let t = capital(SEED, archetype);
            let (weapon, _) = t.turret_arms(SEED);
            let mut game = visit(SEED, t.capital.center());
            let turrets: Vec<Body> = game
                .bodies
                .iter()
                .filter(|b| b.base.as_ref().is_some_and(|s| s.kind == BaseKind::Turret))
                .cloned()
                .collect();
            assert!(!turrets.is_empty());
            assert!(
                turrets
                    .iter()
                    .all(|b| b.base.as_ref().unwrap().arms.unwrap().0 == weapon)
            );
            let mut fired = false;
            for turret in &turrets {
                let FortPart {
                    kind: PartKind::Turret { facing, .. },
                    ..
                } = turret.fort.unwrap()
                else {
                    panic!()
                };
                game.bullets.clear();
                let ship = turret.position + Vec2::from_angle(facing) * 420.0;
                for _ in 0..240 {
                    set_player(&mut game, ship, Vec2::ZERO);
                    game.step(DT, Input::default());
                    if let Some(b) = game
                        .bullets
                        .iter()
                        .find(|b| !b.friendly && b.position.distance(turret.position) < 110.0)
                    {
                        let shape = match weapon {
                            Weapon::Missile => Shape::Missile,
                            Weapon::Needles => Shape::Needle,
                            Weapon::Nova | Weapon::Spiral => Shape::Orb,
                            _ => Shape::Pellet,
                        };
                        assert_eq!(b.shape, shape, "{weapon:?}");
                        fired = true;
                        break;
                    }
                }
                if fired {
                    break;
                }
            }
            assert!(fired, "{archetype:?} turrets never fired");
            checked += 1;
        }
        assert_eq!(checked, 4);
    }

    #[test]
    fn a_turret_behind_a_wall_does_not_fire_and_a_gate_turret_lays_mines() {
        let t = capital(SEED, Archetype::Ring);
        let mut game = visit(SEED, t.capital.center());
        let turret = game
            .bodies
            .iter()
            .find(|b| {
                matches!(
                    b.fort,
                    Some(FortPart {
                        kind: PartKind::Turret { lay: Some(_), .. },
                        ..
                    })
                )
            })
            .cloned()
            .expect("a turret that lays mines");
        let FortPart {
            kind: PartKind::Turret { facing, lay, .. },
            ..
        } = turret.fort.unwrap()
        else {
            panic!()
        };
        // Cover: a wall dropped right in front of the muzzle blocks the line.
        let blocker = Vec2::from_angle(facing) * 120.0 + turret.position;
        let id = crate::simulation::tests::add(&mut game, BodyKind::Asteroid, blocker);
        {
            let b = game.bodies.iter_mut().find(|b| b.id == id).unwrap();
            b.rock = RockKind::Wall;
            b.pinned = true;
            b.radius = 60.0;
        }
        let ship = turret.position + Vec2::from_angle(facing) * 500.0;
        game.bullets.clear();
        for _ in 0..700 {
            set_player(&mut game, ship, Vec2::ZERO);
            game.step(DT, Input::default());
            assert!(
                game.bullets
                    .iter()
                    .all(|b| b.friendly || b.position.distance(turret.position) > 110.0),
                "no shot through cover"
            );
        }
        let spot = lay.unwrap();
        assert!(
            game.mines
                .iter()
                .any(|m| !m.friendly && m.position.distance(spot) < 130.0),
            "a mine sits at the chokepoint"
        );
        assert!(
            game.mines
                .iter()
                .filter(|m| m.position.distance(spot) < 130.0)
                .count()
                <= 2
        );
    }

    #[test]
    fn a_destroyed_turret_pays_scrap_and_stays_gone_and_a_fallen_civilization_goes_quiet() {
        let t = capital(SEED, Archetype::Ring);
        let mut game = visit(SEED, t.capital.center());
        let turret = game
            .bodies
            .iter()
            .find(|b| b.base.as_ref().is_some_and(|s| s.kind == BaseKind::Turret))
            .cloned()
            .unwrap();
        let bases = game.run.bases;
        game.pickups.clear();
        game.bodies
            .iter_mut()
            .find(|b| b.id == turret.id)
            .unwrap()
            .health = 0.0;
        game.step(DT, Input::default());
        assert!(
            game.pickups
                .iter()
                .any(|p| matches!(p.item, Item::Material(Material::Metal, _)))
        );
        assert_eq!(game.run.bases, bases, "a turret is not a station");
        assert!(!game.civ_fall(t.id).capital);
        // Ruin the civilization: the other turrets stop shooting.
        game.civ_fall.insert(
            t.id,
            crate::territory::Fall {
                capital: true,
                elder: true,
            },
        );
        let other = game
            .bodies
            .iter()
            .find(|b| b.base.as_ref().is_some_and(|s| s.kind == BaseKind::Turret))
            .cloned()
            .unwrap();
        let FortPart {
            kind: PartKind::Turret { facing, .. },
            ..
        } = other.fort.unwrap()
        else {
            panic!()
        };
        game.bullets.clear();
        // Wildlife is not what is being judged (an ecosystem Bastion or a gunner species
        // living in the capital's sector shoots at the ship): only the fallen
        // civilization's turrets are.
        game.bodies.retain(|b| {
            b.kind != BodyKind::Creature && (b.kind != BodyKind::Base || b.fort.is_some())
        });
        for _ in 0..300 {
            set_player(
                &mut game,
                other.position + Vec2::from_angle(facing) * 400.0,
                Vec2::ZERO,
            );
            game.step(DT, Input::default());
        }
        assert!(game.bullets.iter().all(|b| b.friendly));
    }

    #[test]
    fn fortress_pieces_are_skipped_near_the_body_cap() {
        let t = capital(SEED, Archetype::Ring);
        let mut game = Game::new(SEED);
        game.player_invulnerability = 1e9;
        // Fill the world to just under the reserve line with dummy rocks.
        while game.bodies.len() + fortress::RESERVE < MAX_BODIES {
            let id = crate::simulation::tests::add(
                &mut game,
                BodyKind::Asteroid,
                Vec2::new(0.0, -2900.0),
            );
            let b = game.bodies.iter_mut().find(|b| b.id == id).unwrap();
            b.pinned = true;
            b.radius = 1.0;
        }
        game.teleport(t.capital.center());
        game.step(DT, Input::default());
        assert_eq!(game.fort_bodies(), 0, "no fortress when the world is full");
    }

    #[test]
    fn long_runs_beside_a_fortress_stay_bounded() {
        let t = capital(SEED, Archetype::Spiral);
        let spot = t.capital.center() + Vec2::new(0.0, 2300.0);
        let mut game = visit(SEED, spot);
        let start = game.fort_bodies();
        assert!(start > 20);
        for _ in 0..8 {
            for _ in 0..(40.0 / 0.05) as usize {
                set_player(&mut game, spot, Vec2::ZERO);
                game.step(0.05, Input::default());
            }
            assert!(game.bodies.len() + game.food.len() + game.eggs.len() < MAX_BODIES);
            assert!(game.fort_bodies() <= start + 140);
            assert!(game.bullets.len() <= MAX_BULLETS && game.mines.len() <= 90);
        }
    }

    #[test]
    fn the_territory_threat_counts_fortification() {
        let t = capital(SEED, Archetype::Grid);
        let mut plain = t;
        plain.capital = SectorId { x: 5, y: 4 };
        assert!(t.fortification() >= 1.0);
        assert!(
            t.menace()
                > (0.85 + 0.35 * t.strength)
                    * match t.shape {
                        CivShape::Horde => 1.0,
                        CivShape::Elder => 1.15,
                        CivShape::Both => 1.3,
                        CivShape::Outpost => 0.4,
                    }
        );
        let _ = plain;
    }
}
